DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0025
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  BIOMEDAP:
    CTX_INIT: "a OCT photo of a"
    # CTX_INIT: "a photo of a"
    N_CTX: 5
    # PREC: "fp32"
    N_PROMPTS: 40
    
    L1_LAMBDA_HIGH: 12.5
    KL_LAMBDA: 0.25
    
    L1_LAMBDA_LOW: 1.0
    LOW_TEMPLATE_TYPE: "minimal"

    ENABLE_FUSION: True
    # ENABLE_FUSION: False
    FUSION_LAYERS: [5, 8]
    # FUSION_LAYERS: [3, 4] # PMCCLIP单独设置
    ALIGNMENT_LAMBDA: 0.1
